-- =================================================================
-- HACKER NEWS ETL PIPELINE — Analytical SQL Queries
-- =================================================================
-- These queries are designed to be run against the `hacker_news.db`
-- SQLite database generated by the etl_pipeline.py script.

-- 1. General Engagement Overview for Front Page
SELECT 
    COUNT(*) AS total_posts,
    ROUND(AVG(points), 1) AS avg_points,
    ROUND(AVG(comments), 1) AS avg_comments,
    MAX(points) AS max_points,
    MAX(comments) AS max_comments
FROM fact_posts;

-- 2. Top 15 Most Frequently Sourced Domains (excluding HN itself)
SELECT 
    domain,
    COUNT(*) AS post_count,
    ROUND(AVG(points), 1) AS avg_points_per_post,
    SUM(points) AS total_domain_points
FROM fact_posts
WHERE domain != 'news.ycombinator.com'
GROUP BY domain
ORDER BY post_count DESC, avg_points_per_post DESC
LIMIT 15;

-- 3. High Engagement Outliers (Top 1% of posts by Points)
-- Uses a subquery to find the 99th percentile threshold dynamically (approximate using ORDER BY)
SELECT 
    title,
    domain,
    points,
    comments
FROM fact_posts
WHERE points > (
    SELECT points 
    FROM fact_posts 
    ORDER BY points DESC 
    LIMIT 1 OFFSET (SELECT CAST(COUNT(*) * 0.05 AS INTEGER) FROM fact_posts) -- Top 5% threshold
)
ORDER BY points DESC;

-- 4. Keyword Trend Analysis (Simulated Full Text Search using LIKE)
SELECT 
    'AI & Machine Learning' AS tech_category,
    COUNT(*) AS post_count,
    ROUND(AVG(points), 1) AS avg_engagement
FROM fact_posts
WHERE title LIKE '% AI %' OR title LIKE '% LLM %' OR title LIKE '% ChatGPT %'

UNION ALL

SELECT 
    'Rust / Go / Systems',
    COUNT(*),
    ROUND(AVG(points), 1)
FROM fact_posts
WHERE title LIKE '% Rust %' OR title LIKE '% Golang %' OR title LIKE '% C++ %'

UNION ALL

SELECT 
    'Startups & Funding',
    COUNT(*),
    ROUND(AVG(points), 1)
FROM fact_posts
WHERE title LIKE '% Startup %' OR title LIKE '% VC %' OR title LIKE '% Funding %';

-- 5. "Show HN" vs "Ask HN" Engagement Comparison
SELECT 
    CASE 
        WHEN title LIKE 'Show HN:%' THEN 'Show HN'
        WHEN title LIKE 'Ask HN:%' THEN 'Ask HN'
        ELSE 'Regular Post'
    END AS post_type,
    COUNT(*) AS total_posts,
    ROUND(AVG(points), 1) AS avg_points,
    ROUND(AVG(comments), 1) AS avg_comments
FROM fact_posts
GROUP BY post_type
ORDER BY avg_points DESC;
